### ISSUE TITLE
Default transform factory functions

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/patternplate#46]
If the factory function of a transform is a real es6 module default export, patternplate refuses to start with:

```
2016-03-06T22:41:53.113Z - error: [patternplate-server] TypeError: factory is not a function
    at /home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/patternplate-server/application/hooks/transforms/index.js:110:60
    at Array.reduce (native)
    at Hook.<anonymous> (/home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/patternplate-server/application/hooks/transforms/index.js:103:64)
    at next (native)
    at step (/home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/patternplate-server/node_modules/babel-runtime/helpers/async-to-generator.js:14:30)
    at /home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/patternplate-server/node_modules/babel-runtime/helpers/async-to-generator.js:28:7
    at new Promise (/home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:186:7)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/patternplate-server/node_modules/babel-runtime/node_modules/core-js/library/modules/$.export.js:30:36)
    at Hook.start (/home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/patternplate-server/node_modules/babel-runtime/helpers/async-to-generator.js:8:12)
    at Hook.<anonymous> (/home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/boilerplate-server/library/hooks/default.js:96:26)
    at next (native)
    at step (/home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/boilerplate-server/library/hooks/default.js:10:273)
    at run (/home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:84:47)
    at /home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:95:28
    at flush (/home/markusw/source/patternplate/typescript-test/node_modules/patternplate/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:19:5)
    at doNTCallback0 (node.js:417:9)
```

This is because patternplate expects transform factories to be exposed at module.exports instead of module.exports.default.
A good way would be to look at module.exports.default and if thats not a function, then try module.exports. Afterwards fail.

**Comment by KnisterPeter** [comment]
See https://github.com/sinnerschrader/patternplate-server/pull/58

**Comment by marionebl** [comment]
https://github.com/sinnerschrader/patternplate-server/pull/58 landed

**Comment by marionebl** [comment]
https://github.com/sinnerschrader/patternplate-server/releases/tag/v0.14.21 released
