### ISSUE TITLE
CSS-only @environments

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate#70]
An …environment with the following config should just generate a CSS output running `patternplate-console build-bundles`:

``` json
{
    "name": "only-css",
    "displayName": "Only CSS",
    "display": true,
    "version": "0.1.0",
    "include": ["*/**"],
    "formats": ["css"],
    "environment": {
        "transforms": {}
    }
}
```

Running this will throw the error:

```
2016-05-25T07:24:43.887Z - error: [patternplate-server] Error while transforming file "<root>/patterns/@environments/frame-das/index.js" of pattern "frame-das" with transform "browserify".
2016-05-25T07:24:43.895Z - info: [patternplate-server] Read pattern "atoms/table" [1969ms]
<root>/node_modules/patternplate/binary/patternplate-console.js:38
        throw err;
        ^

Error: Cannot find module '<root>/patterns/@environments/frame-das/index.js' from '<root>'
    at <root>/node_modules/resolve/lib/async.js:55:21
    at load (<root>/node_modules/resolve/lib/async.js:69:43)
    at onex (<root>/node_modules/resolve/lib/async.js:92:31)
    at <root>/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Adding an `index.js` in the environment folder acts as a workaround but then the output includes an nearly empty JS file including just the commonJS wrapper:

``` JS
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";

},{}]},{},[1]);
;
```

**Comment by marionebl** [comment]
build systems / environment will not be part of patternplate `2.0` and up.
