### ISSUE TITLE
[transform-react]: implicit dependencies produce duplicate import

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/patternplate#72]
Implicit dependencies produce duplicate import statements, throwing `TypeError`s, e.g.:

```
2016-05-26T10:21:52.976Z - error: [patternplate-server] Error in "ecospheres/account/minutes-page" during transform "react" of "~/patterns/ecospheres/account/minutes-page/index.html": unknown: Line 3: Duplicate declaration "MainBarLink"

TypeError: unknown: Line 3: Duplicate declaration "MainBarLink"
  1 | const MainBarLink = require("main-bar-link");
  2 | 
> 3 | const MainBarLink = require("main-bar-link");
    |       ^
  4 | 
  5 | const MainBarLink = require("main-bar-link");
  6 | 
    at File.errorWithNode (~/node_modules/babel-core/lib/transformation/file/index.js:489:13)
    at Scope.checkBlockScopedCollisions (~/node_modules/babel-core/lib/traversal/scope/index.js:412:27)
    at Scope.<anonymous> (~/node_modules/babel-core/lib/traversal/scope/index.js:594:18)
    at Scope.registerBinding (~/node_modules/babel-core/lib/traversal/scope/index.js:608:8)
    at Scope.registerDeclaration (~/node_modules/babel-core/lib/traversal/scope/index.js:528:14)
    at NodePath.BlockScoped (~/node_modules/babel-core/lib/traversal/scope/index.js:140:28)
    at NodePath.<anonymous> (~/node_modules/babel-core/lib/traversal/visitors.js:221:17)
    at NodePath.call (~/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (~/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitMultiple (~/node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (~/node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (~/node_modules/babel-core/lib/traversal/index.js:76:17)
    at Object.traverse [as default] (~/node_modules/babel-core/lib/traversal/index.js:55:14)
    at NodePath.traverse (~/node_modules/babel-core/lib/traversal/path/index.js:163:23)
    at Scope.crawl (~/node_modules/babel-core/lib/traversal/scope/index.js:821:10)
    at Scope.init (~/node_modules/babel-core/lib/traversal/scope/index.js:737:32)
    at NodePath.setScope (~/node_modules/babel-core/lib/traversal/path/context.js:149:30)
    at NodePath.setContext (~/node_modules/babel-core/lib/traversal/path/context.js:168:8)
    at File._addAst (~/node_modules/babel-core/lib/transformation/file/index.js:590:8)
    at File.addAst (~/node_modules/babel-core/lib/transformation/file/index.js:601:10)
    at File.parseCode (~/node_modules/babel-core/lib/transformation/file/index.js:692:10)
    at ~/node_modules/babel-core/lib/transformation/pipeline.js:167:12
```

**Comment by marionebl** [comment]
https://github.com/sinnerschrader/patternplate-transform-react/releases/tag/v0.4.3
